# Copyright (C) 2018-2019 Lienol
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-v2ray-server
LUCI_TITLE:=LuCI support for V2ray Server
LUCI_DEPENDS:=+libsodium +luci-lib-jsonc +unzip +v2ray 
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
77PKG_RELEASE:=28-20191107

include ../luci_my.mk

# call BuildPackage - OpenWrt buildroot signature


