# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for SSR Server By Lienol
LUCI_DEPENDS:=+python
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=20181106

include $(TOPDIR)/package/lienol/luci_my.mk

# call BuildPackage - OpenWrt buildroot signature


