#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Netgear Theme
LUCI_DEPENDS:=
PKG_VERSION:=1.0
PKG_RELEASE:=13-20190316

include ../luci_my.mk

# call BuildPackage - OpenWrt buildroot signature
