#!/bin/sh /etc/rc.common

START=99

IPSEC_SECRETS_FILE=/etc/ipsec.secrets
IPSEC_CONN_FILE=/etc/ipsec.conf

add_rule() {
	iptables -t nat -I POSTROUTING -s ${vt_clientip%.*}.0/24 -m comment --comment "IPSec VPN Server" -j MASQUERADE
	iptables -I forwarding_rule -s ${vt_clientip%.*}.0/24 -m comment --comment "IPSec VPN Server" -j ACCEPT
	iptables -I forwarding_rule -m policy --dir in --pol ipsec --proto esp -m comment --comment "IPSec VPN Server" -j ACCEPT
	iptables -I forwarding_rule -m policy --dir out --pol ipsec --proto esp -m comment --comment "IPSec VPN Server" -j ACCEPT
	iptables -I INPUT -p udp -m multiport --dports 500,4500 -m comment --comment "IPSec VPN Server" -j ACCEPT
}

del_rule() {
	iptables -D INPUT -p udp -m multiport --dports 500,4500 -m comment --comment "IPSec VPN Server" -j ACCEPT 2> /dev/null
	ipsec_nums=$(iptables -t nat -n -L POSTROUTING 2>/dev/null | grep -c "IPSec VPN Server")
	if [ -n "$ipsec_nums" ]; then
		until [ "$ipsec_nums" = 0 ]
		do
			rules=$(iptables -t nat -n -L POSTROUTING --line-num 2>/dev/null | grep "IPSec VPN Server" | awk '{print $1}')
			for rule in $rules
			do
				iptables -t nat -D POSTROUTING $rule 2> /dev/null
				break
			done
			ipsec_nums=$(expr $ipsec_nums - 1)
		done
	fi
	nums=$(iptables -n -L forwarding_rule 2>/dev/null | grep -c "IPSec VPN Server")
	if [ -n "$nums" ]; then
		until [ "$nums" = 0 ]
		do
			rules=$(iptables -n -L forwarding_rule --line-num 2>/dev/null | grep "IPSec VPN Server" | awk '{print $1}')
			for rule in $rules
			do
				iptables -D forwarding_rule $rule 2> /dev/null
				break
			done
			nums=$(expr $nums - 1)
		done
	fi
}

gen_include() {
	echo '#!/bin/sh' > /var/etc/ipsecvpn.include
	extract_rules() {
		echo "*$1"
		iptables-save -t $1 | grep "IPSec VPN Server" | \
		sed -e "s/^-A \(INPUT\)/-I \1 1/"
		echo 'COMMIT'
	}
	cat <<-EOF >> /var/etc/ipsecvpn.include
		iptables-save -c | grep -v "IPSec VPN Server" | iptables-restore -c
		iptables-restore -n <<-EOT
		$(extract_rules filter)
		$(extract_rules nat)
		EOT
	EOF
	return 0
}

setup_login() {
	config_get enabled $1 enabled
	[ "$enabled" -eq 0 ] && return 0
	config_get username $1 username
	config_get password $1 password
	[ -n "$username" ] || return 0
	[ -n "$password" ] || return 0
	echo "$username : XAUTH '$password'" >> $IPSEC_SECRETS_FILE
}

start() {
	local vt_enabled=$(uci -q get ipsec.@service[0].enabled)
	[ "$vt_enabled" = 0 ] && return 1
	
	local vt_clientip=$(uci -q get ipsec.@service[0].clientip)
	local vt_clientdns=$(uci -q get ipsec.@service[0].clientdns)
	[ -z "$vt_clientdns" ] && local vt_clientdns="8.8.4.4"
	local vt_secret=$(uci -q get ipsec.@service[0].secret)
	
	cat > $IPSEC_CONN_FILE <<EOF
# ipsec.conf - strongSwan IPsec configuration file

# basic configuration

config setup
    # strictcrlpolicy=yes
    uniqueids=never

# Add connections here.

conn xauth_psk
	keyexchange=ikev1
	ike=aes128-sha1-modp2048,aes128-sha1-modp1024,3des-sha1-modp1024,3des-sha1-modp1536
  esp=aes128-sha1,3des-sha1
	left=%defaultroute
	leftauth=psk
	leftsubnet=0.0.0.0/0
	right=%any
	rightauth=psk
	rightauth2=xauth
	rightsourceip=$vt_clientip
	rightdns=$vt_clientdns
	auto=add
EOF

	cat > /etc/ipsec.secrets <<EOF
# /etc/ipsec.secrets - strongSwan IPsec secrets file
: PSK "$vt_secret"
EOF

	add_rule
	
	config_load ipsec
	config_foreach setup_login users
	
	/usr/lib/ipsec/starter --daemon charon --nofork > /dev/null 2>&1 &
	gen_include
}

stop() {
	ps -w | grep "/usr/lib/ipsec" | grep -v "grep" | awk '{print $1}' | xargs kill -9 >/dev/null 2>&1
	del_rule
	rm -rf /var/etc/ipsecvpn.include
}