#!/bin/sh /etc/rc.common
# Copyright (C) 2018 Lienol <lienol@qq.com>

START=90
STOP=16

CONFIG="pppoe-server"
CONFIG_FILE=/etc/ppp/pppoe-server-options
CHAP_SECRETS=/var/etc/chap-secrets
TEMP=/tmp/pppoe-server.tmp
SERVER_NAME="pppoe-server"

uci_get_by_type() {
	local index=0
	if [ -n $4 ]; then
		index=$4
	fi
	local ret=$(uci get $CONFIG.@$1[$index].$2 2>/dev/null)
	echo ${ret:=$3}
}

setup_users() {
	local section="$1"
	config_get enabled "$section" enabled
	[ "$enabled" -eq 0 ] && return 0
	config_get username "$section" username
	config_get password "$section" password
	config_get ipaddress "$section" ipaddress
	[ -n "$username" ] || return 0
	[ -n "$password" ] || return 0
	echo "$username $SERVER_NAME $password $ipaddress" >> $CHAP_SECRETS
}

del_user()
{
	cat $CHAP_SECRETS | grep -v $SERVER_NAME > $TEMP
	cat $TEMP > $CHAP_SECRETS
	rm $TEMP
}

start() {
	config_load pppoe-server
	enabled=$(uci_get_by_type service enabled)
	[ "$enabled" -eq 0 ]  && exit 0
	cat <<-EOF >$CONFIG_FILE
# PPP options for the PPPoE server
# LIC: GPL
name $SERVER_NAME
login
require-mschap-v2
refuse-chap
require-pap
lcp-echo-interval 10
lcp-echo-failure 2
mru $(uci_get_by_type service mru 1492)
mtu $(uci_get_by_type service mtu 1492)
ms-dns $(uci_get_by_type service dns1 223.5.5.5)
ms-dns $(uci_get_by_type service dns2 119.29.29.29)
logfile $(uci_get_by_type service log /var/log/pppoe-server.log)
EOF
	del_user
	config_foreach setup_users user
	ln -sfn $CHAP_SECRETS /etc/ppp/chap-secrets
	local is_nat=$(uci_get_by_type service is_nat)
	local localip=$(uci_get_by_type service localip)
	if [ "$is_nat" -eq 1 ];then
		local export_interface=$(uci_get_by_type service export_interface)
		if [ "$export_interface" != "default" ];then
			iptables -t nat -A POSTROUTING -s ${localip%.*}.0/24 -o ${export_interface} -m comment --comment "Rule For PPPoE Server" -j MASQUERADE
		else
			iptables -t nat -A POSTROUTING -s ${localip%.*}.0/24 -m comment --comment "Rule For PPPoE Server" -j MASQUERADE
		fi
		iptables -A forwarding_rule -s ${localip%.*}.0/24 -m comment --comment "Rule For PPPoE Server" -j ACCEPT
	fi
	/usr/sbin/pppoe-server -k -I $(uci_get_by_type service client_interface) -L $(uci_get_by_type service localip) -R $(uci_get_by_type service remoteip) -N $(uci_get_by_type service count)
}

stop() {
	del_user
	nums=`iptables -t nat -L POSTROUTING 2> /dev/null|grep -c "Rule For PPPoE Server"`
	if [ -n "$nums" ]; then
		until [ "$nums" = 0 ]
		do
			rules=`iptables -t nat -L POSTROUTING --line-num 2> /dev/null|grep "Rule For PPPoE Server" |awk '{print $1}'`
			for rule in $rules
			do
					iptables -t nat -D POSTROUTING $rule 2> /dev/null
					break
			done
			nums=`expr $nums - 1`
		done
	fi
	nums2=`iptables -L forwarding_rule 2> /dev/null|grep -c "Rule For PPPoE Server"`
	if [ -n "$nums2" ]; then
		until [ "$nums2" = 0 ]
		do
			rules=`iptables -L forwarding_rule --line-num 2> /dev/null|grep "Rule For PPPoE Server" |awk '{print $1}'`
			for rule in $rules
			do
					iptables -D forwarding_rule $rule 2> /dev/null
					break
			done
			nums2=`expr $nums2 - 1`
		done
	fi
	ps | grep "pppd plugin rp-pppoe.so" | grep -v "grep" | awk '{print $1}' | xargs kill -9
	killall -9 pppoe-server
}
