# Copyright (C) 2018-2019 Lienol <lawlienol@gmail.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Bootstrap Magic Change Theme By Lienol
LUCI_DEPENDS:=
PKG_VERSION:=1.0
PKG_RELEASE:=40-20191207

include ../luci_my.mk

# call BuildPackage - OpenWrt buildroot signature
