#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@ssr_server[-1]
	add ucitrack ssr_server
	set ucitrack.@ssr_server[-1].init=ssr_server
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
