# Copyright (C) 2018-2019 Lienol
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Netgear Magic Change Theme
LUCI_DEPENDS:=
PKG_VERSION:=1.0
PKG_RELEASE:=15-20190503

include ../luci_my.mk

# call BuildPackage - OpenWrt buildroot signature
