#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.ssr_python_pro_server
	set firewall.ssr_python_pro_server=include
	set firewall.ssr_python_pro_server.type=script
	set firewall.ssr_python_pro_server.path=/usr/share/ssr_python_pro_server/firewall.include
	set firewall.ssr_python_pro_server.reload=1
EOF

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@ssr_python_pro_server[-1]
	add ucitrack ssr_python_pro_server
	set ucitrack.@ssr_python_pro_server[-1].init=ssr_python_pro_server
	commit ucitrack
EOF

chmod a+x /usr/share/ssr_python_pro_server/* >/dev/null 2>&1

rm -f /tmp/luci-indexcache
exit 0
