#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.brook_server
	set firewall.brook_server=include
	set firewall.brook_server.type=script
	set firewall.brook_server.path=/var/etc/brook_server.include
	set firewall.brook_server.reload=1
EOF

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@brook_server[-1]
	add ucitrack brook_server
	set ucitrack.@brook_server[-1].init=brook_server
	commit ucitrack
EOF

rm -rf /tmp/luci-*cache
exit 0
