#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.brook_server
	set firewall.brook_server=include
	set firewall.brook_server.type=script
	set firewall.brook_server.path=/usr/share/brook_server/firewall.include
	set firewall.brook_server.reload=1
EOF

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@brook_server[-1]
	add ucitrack brook_server
	set ucitrack.@brook_server[-1].init=brook_server
	commit ucitrack
EOF

chmod a+x /usr/share/brook_server/* >/dev/null 2>&1

rm -f /tmp/luci-indexcache
exit 0
