#!/bin/sh /etc/rc.common

START=99
CONFIG=pptpd
CONFIG_FILE=/var/etc/$CONFIG.conf
RUN_D=/var/run
CHAP_SECRETS=/var/etc/chap-secrets
SERVER_NAME="pptp-server"
TEMP=/tmp/pptpd.tmp

setup_login() {
	config_get enabled $1 enabled
	[ "$enabled" -eq 0 ] && return 0
	config_get ipaddress $1 ipaddress
	[ -n "$ipaddress" ] || local ipaddress="*"
	config_get username $1 username
	config_get password $1 password
	[ -n "$username" ] || return 0
	[ -n "$password" ] || return 0
	echo "$username $SERVER_NAME $password $ipaddress" >> $CHAP_SECRETS
}

setup_config() {
	config_get enabled $1 enabled
	[ "$enabled" -eq 0 ] && return 1

	mkdir -p /var/etc
	cp /etc/pptpd.conf $CONFIG_FILE
	
	config_get localip $1 localip
	config_get remoteip $1 remoteip

	[ -z "$localip" ] && localip="172.16.100.1"
	[ -z "$remoteip" ] && remoteip="172.16.100.10-20"
	[ -n "$localip" ] && echo "localip  $localip" >> $CONFIG_FILE
	[ -n "$remoteip" ] && echo "remoteip  $remoteip" >> $CONFIG_FILE
	echo "option /etc/ppp/options.pptpd" >> $CONFIG_FILE

	fw3 reload >/dev/null 2>&1
	
	config_get mppe $1 mppe
	if [ -n "$(cat "/etc/ppp/options.pptpd" | grep mppe)" ]; then
		sed -i '/mppe/'d /etc/ppp/options.pptpd
	else
		echo "mppe required,no40,no56,stateless" >> /etc/ppp/options.pptpd
	fi
	[ "$mppe" -eq 0 ] && sed -i -e 's/mppe/#mppe/g' /etc/ppp/options.pptpd
	sed -i -e '/ms-dns/d' /etc/ppp/options.pptpd
	config_get dns $1 dns
	[ -z "$dns" ] && dns="8.8.4.4"
	echo "ms-dns $dns">>/etc/ppp/options.pptpd
	return 0
}

start_pptpd() {
	mkdir -p $RUN_D
	for m in arc4 sha1_generic slhc crc-ccitt ppp_generic ppp_async ppp_mppe; do
		insmod $m >/dev/null 2>&1
	done
	ln -sfn $CHAP_SECRETS /etc/ppp/chap-secrets
	chmod 600 /etc/ppp/*-secrets
	/usr/sbin/$CONFIG -c $CONFIG_FILE
}

del_user()
{
	cat $CHAP_SECRETS | grep -v $SERVER_NAME > $TEMP
	cat $TEMP > $CHAP_SECRETS
	rm $TEMP
}

start() {
	config_load $CONFIG
	setup_config $CONFIG || return
	del_user
	config_foreach setup_login users
	start_pptpd
}

stop() {
	ps -w | grep "$CONFIG_FILE" | grep -v "grep" | awk '{print $1}' | xargs kill -9 >/dev/null 2>&1
	ps -w | grep "pppd local" | grep -v "grep" | awk '{print $1}' | xargs kill -9 >/dev/null 2>&1
	fw3 reload >/dev/null 2>&1
	del_user
}
