# Copyright (C) 2018-2019 Lienol
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for SSR Python Pro Server
LUCI_DEPENDS:=+libsodium +luci-lib-jsonc +python
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=2-20190501

include ../luci_my.mk

# call BuildPackage - OpenWrt buildroot signature


