# Copyright (C) 2019 Lienol
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-brook-server
LUCI_TITLE:=LuCI support for Brook Server
LUCI_DEPENDS:=+brook 
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=1-20191120

include ../luci_my.mk

# call BuildPackage - OpenWrt buildroot signature


