#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.trojan_server
	set firewall.trojan_server=include
	set firewall.trojan_server.type=script
	set firewall.trojan_server.path=/var/etc/trojan_server.include
	set firewall.trojan_server.reload=1
EOF

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@trojan_server[-1]
	add ucitrack trojan_server
	set ucitrack.@trojan_server[-1].init=trojan_server
	commit ucitrack
EOF

rm -rf /tmp/luci-*cache
exit 0
