#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.trojan_server
	set firewall.trojan_server=include
	set firewall.trojan_server.type=script
	set firewall.trojan_server.path=/usr/share/trojan_server/firewall.include
	set firewall.trojan_server.reload=1
EOF

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@trojan_server[-1]
	add ucitrack trojan_server
	set ucitrack.@trojan_server[-1].init=trojan_server
	commit ucitrack
EOF

chmod a+x /usr/share/trojan_server/* >/dev/null 2>&1

rm -f /tmp/luci-indexcache
exit 0
