#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@server_center[-1]
	add ucitrack server_center
	set ucitrack.@server_center[-1].init=server_center
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
