# Copyright (C) 2019 Lienol
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-trojan-server
LUCI_TITLE:=LuCI support for Trojan Server
LUCI_DEPENDS:=+luci-lib-jsonc +trojan 
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=2-20191207

include ../luci_my.mk

# call BuildPackage - OpenWrt buildroot signature


