# Copyright (C) 2018 Lienol
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for SSR Server Python
LUCI_DEPENDS:=+python
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=5-20190112

include $(TOPDIR)/package/lienol/luci_my.mk

# call BuildPackage - OpenWrt buildroot signature


