#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Bootstrap Theme Blue By Lienol
LUCI_DEPENDS:=
PKG_VERSION:=1.0
PKG_RELEASE:=20181107

include $(TOPDIR)/package/lienol/luci_my.mk

# call BuildPackage - OpenWrt buildroot signature
