#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@homeassistant[-1]
	add ucitrack homeassistant
	set ucitrack.@homeassistant[-1].init=homeassistant
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
