# Copyright (C) 2008-2019 Jerrykuku
# Copyright (C) 2019 Lienol
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Argon Mod Theme
LUCI_DEPENDS:=
PKG_VERSION:=1.5
PKG_RELEASE:=08-20191221

include ../luci_my.mk

# call BuildPackage - OpenWrt buildroot signature
