# Copyright (C) 2018-2020 Lienol <lawlienol@gmail.com>
#
# This is free software, licensed under the GNU General Public License v3.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Bootstrap Mod Theme By Lienol
LUCI_DEPENDS:=
PKG_VERSION:=1.1
PKG_RELEASE:=3-20200303

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
