# Copyright (C) 2018 Lienol
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for PPPoE Relay
LUCI_DEPENDS:=+rp-pppoe-common +rp-pppoe-relay
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=8-20190412

include ../luci_my.mk

# call BuildPackage - OpenWrt buildroot signature


