#!/bin/sh /etc/rc.common
#
# Copyright (C) 2018 Lienol
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=99
STOP=16

CONFIG=ssr_server
CONFIG_FILE=/var/etc/$CONFIG.json
PID_FILE=/var/run/$CONFIG.pid
LOG_FILE=/var/log/$CONFIG.log
USERS=""
REDIRECTS=""

config_t_get() {
	local index=0
	[ -n "$4" ] && index=$4
	local ret=$(uci get $CONFIG.@$1[$index].$2 2>/dev/null)
	echo ${ret:=$3}
}

start_server() {
	mkdir -p /var/etc
	/usr/bin/python /usr/share/ssr/shadowsocks/server.py -c $CONFIG_FILE --pid-file $PID_FILE --log-file $LOG_FILE -d start >/dev/null 2>&1 &
}

gen_config_file() {
	config_foreach setup_users users
	FINAL=`echo $USERS | sed 's/\(.*\)\(.\)$/\2/'`
	[ "$FINAL" == "," ] && USERS=`echo $USERS | sed 's/\(.*\)\(.\)$/\1/'`
	
	redirect=$(config_t_get server redirect)
	for i in $redirect
	do
		REDIRECTS="$REDIRECTS\"$i\","
	done
	FINAL=`echo $REDIRECTS | sed 's/\(.*\)\(.\)$/\2/'`
	[ "$FINAL" == "," ] && REDIRECTS=`echo $REDIRECTS | sed 's/\(.*\)\(.\)$/\1/'`
	cat <<-EOF >$CONFIG_FILE
		{
		    "server": "::",
		    "local_address":"127.0.0.1",
		    "local_port":1086,
			"port_password": {$USERS},
		    "timeout": $(config_t_get server timeout 300),
		    "method": "$(config_t_get server encrypt_method)",
		    "protocol": "$(config_t_get server protocol)",
		    "protocol_param": "$(config_t_get server protocol_param)",
		    "obfs": "$(config_t_get server obfs)",
		    "obfs_param": "$(config_t_get server obfs_param)",
			"connect_verbose_info": "1",
		    "redirect": [$REDIRECTS],
		    "fast_open": "$(config_t_get server fast_open)"
		}
EOF
}

setup_users() {
	config_get enabled $1 enabled
	[ "$enabled" -eq 0 ] && return 0
	config_get port $1 port
	config_get password $1 password
	[ -n "$port" -a -n "$password" ] && USERS=$USERS"\"$port\"":"\"$password\"",
}

start() {
	stop
	config_load $CONFIG
	ENABLED=$(config_t_get server enable 0)
	[ "$ENABLED" = "0" ] && return 0
	gen_config_file
	start_server
}

stop() {
	ps | grep "/usr/bin/python /usr/share/ssr/shadowsocks/server.py" | grep -v "grep" | awk '{print $1}' | xargs kill -9
	rm -f $PID_FILE
	rm -f $LOG_FILE
	rm -f $CONFIG_FILE
}

restart() {
	stop
	sleep 1
	start
}